### ISSUE TITLE
AccessDenied: Access Denied

### ISSUE THREAD

**Issue by skghosh-invn** [DanielHindi/aws-s3-zipper#16]
I am getting the following error trying to use this module:
`Debug: internal, implementation, error 
    AccessDenied: Access Denied
    at Request.extractError (<somepath>/aws-s3-zipper/node_modules/aws-sdk/lib/services/s3.js:334:35)
    at Request.callListeners (<somepath>/aws-s3-zipper/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (<somepath>/aws-s3-zipper/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (<somepath>/aws-s3-zipper/node_modules/aws-sdk/lib/request.js:596:14)
    at Request.transition (<somepath>/aws-s3-zipper/node_modules/aws-sdk/lib/request.js:21:10)`

When I am using the same credentials I am able to list the Objects in the Prefix using aws-sdk  2.56

In this code piece - 
`        var client = s3.createClient(options);

        var realParams = {
            s3Params: bucketParams,
            recursive: params.recursive
        };

        var emitter = client.listObjects(realParams);`

Looks like the aws version is being used here is 2.2 So, if I try to use a similar json format for listObjects with `s3Params` it says 
`* MissingRequiredParameter: Missing required key 'Bucket' in params
* UnexpectedParameter: Unexpected key 's3Params' found in params`

Found out that the emitter is not getting the data or end event.
Any Help is appreciated.

**Comment by Sin3W** [comment]
did you get any solution on this?
