### ISSUE TITLE
non-recursive?

### ISSUE THREAD

**Issue by 4fthawaiian** [DanielHindi/aws-s3-zipper#5]
Hi there,

Just wondering if this is meant to be non-recursive. I've got a "folder" in a bucket with several "sub-folders" (the quotes are to indicate that yes, I realize there are just keys, and files, but no real folders).

The structure is something like:
```
bucket
    base folder
        user folder
            <various sub folders with sub-folders and files underneath>
```

I'm calling the zip on "base folder/user folder" and because there aren't any files here, merely folders, I'm getting "no files zipped. nothing to upload".

If I drop a file in the "user folder" the zipToS3File call zips up that file, but doesn't find any of the files/folders living under the other folders.

I'm going to see if I can make a patch to make this work (I've actually done this by hand with the s3 sdk, but I want to see if your stuff is faster) but anything you can contribute would be much appreciated.

Cheers, and thanks for the npm module. Nice stuff, I think ;)

**Comment by DanielHindi** [comment]
Hello,

I have a pull request from a fellow contributor that does this https://github.com/DanielHindi/aws-s3-zipper/pull/2

If you test it and it works for you I'll merge it it. Based on a visual review it looks good. Lots of formatting checkins which makes it harder to check. My only comment on it is that the recursive nature is not passed as a parameter to make it optional.

**Comment by 4fthawaiian** [comment]
This is awesome. Thanks for the quick response!

I'll test and get back to you shortly.

**Comment by 4fthawaiian** [comment]
ok - it did work, but I now have a different error:

```
/Users/bradleymccrorey/lambdazip/node_modules/aws-s3-zipper/node_modules/aws-sdk/lib/request.js:30
            throw err;
            ^

TypeError: Cannot read property 'ETag' of undefined
    at /Users/bradleymccrorey/lambdazip/node_modules/aws-s3-zipper/index.js:224:44
    at ManagedUpload.callback (/Users/bradleymccrorey/lambdazip/node_modules/aws-s3-zipper/index.js:203:21)
    at Response.finishSinglePart (/Users/bradleymccrorey/lambdazip/node_modules/aws-s3-zipper/node_modules/aws-sdk/lib/s3/managed_upload.js:568:28)
    at Request.<anonymous> (/Users/bradleymccrorey/lambdazip/node_modules/aws-s3-zipper/node_modules/aws-sdk/lib/request.js:354:18)
    at Request.callListeners (/Users/bradleymccrorey/lambdazip/node_modules/aws-s3-zipper/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/bradleymccrorey/lambdazip/node_modules/aws-s3-zipper/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/bradleymccrorey/lambdazip/node_modules/aws-s3-zipper/node_modules/aws-sdk/lib/request.js:596:14)
    at Request.transition (/Users/bradleymccrorey/lambdazip/node_modules/aws-s3-zipper/node_modules/aws-sdk/lib/request.js:21:10)
    at AcceptorStateMachine.runTo (/Users/bradleymccrorey/lambdazip/node_modules/aws-s3-zipper/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/bradleymccrorey/lambdazip/node_modules/aws-s3-zipper/node_modules/aws-sdk/lib/state_machine.js:26:10
```

Pretty sure this is a completely different issue. So, if you're looking to merge in that pull request, you're probably good to go. Thanks again for the help.

**Comment by DanielHindi** [comment]
there is a conflict. I'm checking it now

**Comment by DanielHindi** [comment]
try version 1.0.1
